### ISSUE TITLE
use jemalloc as memory pool

### ISSUE THREAD

**Issue by dragon-zhang** [alibaba/PhotonLibOS#108]
I see that `posix_memalign` is currently used to allocate memory. Maybe `jemalloc` would be better?

**Comment by beef9999** [comment]
Do you mean using jemalloc to replace posix_memalign? Or replace the whole memory pool?

BTW, photon uses the `IOAlloc` interface to representing a memory allocator. The `PooledAllocator` is something you can use to generate a `IOAlloc`, which can manage memory with a pool.

Of course you can implement you own allocator, as long as it satisfied the IOAlloc interface

**Comment by dragon-zhang** [comment]
At first, I thought there was no memory pool, but it has.
