### ISSUE TITLE
Compare with seastar ?

### ISSUE THREAD

**Issue by luliyucoordinate** [alibaba/PhotonLibOS#111]
Is there a comparison test with [seastar](https://github.com/scylladb/seastar) ?

**Comment by beef9999** [comment]
I didn't find an available example from its demos. The only echo server was based on DPDK.

If you can provide a echo server based on tcp socket, I'm willing to have a try.

**Comment by beef9999** [comment]
@luliyucoordinate Photon 0.6 is going to release. It now support running on F-Stack + DPDK.

|            Server socket type             | Client traffic type (ping-pong) | Client traffic type (stream) |
|:-----------------------------------------:|:-------------------------------:|:----------------------------:| 
|  Linux 6.x kernel + io_uring + coroutine  |            1.03Gb/s             |           2.60Gb/s           |
| photon + f-stack + DPDK |            1.23Gb/s             |           3.74Gb/s           | 

Would you like to compare photon with seastar?
