### ISSUE TITLE
How to implement streaming client that terminates after data transfer completion

### ISSUE THREAD

**Issue by aley1** [alibaba/PhotonLibOS#121]
Hi,

I am hoping someone could please advise or guide me on how to do this asynchronously with PhotonLibOS:

I have a server (A) application that needs to send one message (e.g. byte array) to a PhotonLibOS TCP server (B) and receive many messages in return. Once B has no more data to send  it will send a final message to indicate the transfer has completed.
Then A will then terminate the client connection.

i have tried to do this using example from https://github.com/alibaba/PhotonLibOS/blob/main/examples/perf/net-perf.cpp

The TCP server (B) is working. It can receive message and write many messages back.
The Client (A) can sent a message and receive multiple messages.
However I don't know how to implement the client in such a way that it is just a function that will terminate the connection and return to the calling function.
The example for echo server/client is a client that is long running on a thread and just goes to sleep.

Any help will be much appreciated. Thank you.

**Comment by beef9999** [comment]
Pease define the meaning of ‘receive many messages’. Is the message length evaluated at runtime in the server side?

Based on your description, I assume you should use photon::rpc, which will allow you to extend response buffer dynamically.

**Comment by aley1** [comment]
Thanks for the reply, I will take a look at the rpc implementation.

**Comment by lihuiba** [comment]
> The TCP server (B) is working. It can receive message and write many messages back.
> The Client (A) can sent a message and receive multiple messages.
> However I don't know how to implement the client in such a way that it is just a function that will terminate the connection and return to the calling function.

You can terminate the connection by close()ing it or by just delete -ing the socket, then return.

> how to do this asynchronously with PhotonLibOS
if you wang to make this function asynchronous, you can create a new thread and let it run the function you have already implemented.
