### ISSUE TITLE
Creating and joining a number of threads only known at runtime

### ISSUE THREAD

**Issue by aley1** [alibaba/PhotonLibOS#124]
Hi,

Is there a way to create and then join photon threads dynamically during runtime without specifying the number during build time. I don't see this in the documentation

example with pseudo code that will create multiple threads and wait for all to complete before moving on to the next 

```
num_of_threads = user_input;  // e.g.  4
thread tasks [num_of_threads];
for(int i=0; i < num_of_threads; i++){
    
    auto my_thread = .....  // create new thread
    tasks[i] = my_thread;
}

// Similar to .waitAll() in other languages that waits for all threads to complete
for(int i=0; i < num_of_threads; i++){
    
     thread_join(tasks[i]);   
}

// continue with code after all threads completed.....
```

**Comment by lihuiba** [comment]
You may want to use this function:
`
void threads_create_join(uint64_t n, thread_entry start, void* arg,
                          uint64_t stack_size = DEFAULT_STACK_SIZE);
`

**Comment by lihuiba** [comment]
Alternatively, you can create a thread pool first, then create threads with that pool, finally join that pool.

**Comment by beef9999** [comment]
@aley1 The `waitAll()` is just an encapsulation. Inside it you still need to manage the thread ids.

Is that you met some issues when using our API model?

```c++
    auto th = photon::thread_create11([&]{
        // ...    
    });
    photon::thread_enable_join(th);
    photon::thread_join((photon::join_handle*) th);
```

```c++
    auto th = new photon_std::thread([&]{
        // ...    
    });
    th->join();
    delete th;
```

**Comment by aley1** [comment]
Hi @lihuiba 
> You may want to use this function: `void threads_create_join(uint64_t n, thread_entry start, void* arg, uint64_t stack_size = DEFAULT_STACK_SIZE);`
- I believe I have to pass the same arg value to all the threads when using this function? I am looking to pass different values to different threads to so that each thread can work on different set of data. Otherwise this function is close to what I need.

Hi @beef9999  I think the photon library is great and API is simple to use. Just that I have a use case where I need to call x number of threads (only known during runtime) and pass different data to each thread and then join them all.

In your example, I need to know many threads to create when I am writing the application.  But in my use case I don't know the amount - could be 10-20 threads. And each thread needs to be given different data. 

I was wondering if you have functions that call automate this.

**Comment by beef9999** [comment]
I think this is just how C++ programs supposed to be written, no other unnecessary encapsulations except for std:: or STL.

‘’’c++
std::vector<YourDataStruct> data(input_num);
for (int i = 0; i < data.size(); ++i)
    photon::thread_create11([&](int index){
        data[i]
    });
‘’’

**Comment by beef9999** [comment]
Yes, join is still needed.

BTW, creating a new photon thread would consume some CPU resources, even it’s relatively less than the std::thread. To minimize the performance impact to the lowest, you may want to use the `thread_pool`

**Comment by lihuiba** [comment]
> * I believe I have to pass the same arg value to all the threads when using this function? I am looking to pass different values to different threads to so that each thread can work on different set of data. Otherwise this function is close to what I need.

So you may want to use the thread_pool, and join the entire thread_poll.

**Comment by aley1** [comment]
Thank you all for your replies. I should have read these examples in /thread/test/perf_workpool.cpp before posting my comment.

I'm now using a thread pool and adapted the code below for my use case.

`    std::vector<photon::join_handle*> jhs;
    auto start = photon::now;
    for (uint64_t i = 0; i < concurrent; i++) {
        jhs.emplace_back(
            photon::thread_enable_join(photon::thread_create(task, (void*)i)));
    }
    for (auto& x : jhs) {
        photon::thread_join(x);
    }`

**Comment by lihuiba** [comment]
void* arg is commonly used in low-level c/c++ interfaces. Actually you can cast any compatible types to that, and cast back in the thread body of course.

Compatible types includes (not limited to): all pointers, all integers not bigger than 8 bytes, char, bool, etc.

For example, suppose you want to pass an int to the new thread, you can write cast as (void*)(int64_t)x, and (int)(int64_t)y to cast back.

**Comment by aley1** [comment]
I have tested the thread library, tcp server/client, and all works fine. But I have problems with the http server. using code from your /tests dir.

`class SimpleHandler : public photon::net::http::HTTPHandler {
public:
    int handle_request(photon::net::http::Request& req, photon::net::http::Response& resp, std::string_view) {
        auto target = req.target();
        resp.set_result(200);
        resp.headers.content_length((size_t) 4096);
        resp.headers.insert("Server", "nginx/1.14.1");
        resp.headers.insert("Content-Type", "application/octet-stream");
        string r = "http server online";
        std::byte header_bytes[r.length()];
        std::memcpy(header_bytes, r.data(), r.length());

          return 0;
    }
};


int HttpServer(){
    auto tcpserv = photon::net::new_tcp_socket_server();
    tcpserv->bind(5000);
    tcpserv->listen();
    DEFER(delete tcpserv);
    auto http_srv = photon::net::http::new_http_server();
    DEFER(delete http_srv);
    SimpleHandler handler;

    tcpserv->set_handler(http_srv->get_connection_handler());
    tcpserv->start_loop(true);

    return 0;
}
`
Whenever I try to build I get an error like this:
_undefined reference to `photon::net::http::Response::set_result(int, std::basic_string_view<char, std::char_traits<char> >)'
undefined reference to `photon::net::http::HeadersBase::insert(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, int)'_

I am not sure why it cannot link or find the reference for these methods in Response. Everything else works except this few lines of code.

**Comment by aley1** [comment]
cmake_minimum_required(VERSION 3.24)
project(myproject)

set(CMAKE_CXX_STANDARD 20)
add_library(libphoton SHARED IMPORTED)

add_executable(myproject main.cpp)
find_library(PHOTON libphoton.so lib)
target_link_libraries(myproject LINK_PUBLIC ${PHOTON}

**Comment by beef9999** [comment]
string -> std::string ?

FetchContent is recommended. https://github.com/alibaba/PhotonLibOS/blob/main/doc/CMakeLists.txt

**Comment by aley1** [comment]
std::string does not affect it. I tried with the CMakeList example with FetchContent. Still the same error. not sure why.

**Comment by beef9999** [comment]
Looks like the root cause is gcc version or c++ std version.

Photon is using C++14. Theoretically 17 and 20 is supported. But had not been tested. Could you change the `CMAKE_CXX_STANDARD` to 17 and try again?

**Comment by aley1** [comment]
I am working on stream processing project - parsing unstructured data to json then doing aggregations on it as well.

**Comment by aley1** [comment]
> Looks like the root cause is gcc version or c++ std version. What is your environment like?
> 
> Photon is using C++14. Theoretically 17 and 20 is supported. But had not been tested. Could you change the `CMAKE_CXX_STANDARD` to 17 and try again?

Tried with 17 and same error. I cannot set it to lower than 17 for my project. It only seems the http Response object is affected. Perhaps there is code in there that 17 and above does not support?

**Comment by beef9999** [comment]
I have just reproduced this error with C++17. Will try to fix it

**Comment by beef9999** [comment]
The reason seems to relate to the `<string_view>` header.

C++14 and C++17 have different symbols of std::string_view. One is `std::basic_string_view<char, std::char_traits >` and the other is `std::basic_string_view<char>`

Photon's CMakeLists.txt has explicitly specified C++14, while your app is C++17. You might need a patch to change Photon's C++ version, and place it in the FetchContent part of your Cmake.

```CMake
FetchContent_Declare(
        photon
        GIT_REPOSITORY https://github.com/alibaba/PhotonLibOS.git
        GIT_TAG v0.4.0
        PATCH_COMMAND git apply a.patch
)
FetchContent_MakeAvailable(photon)
```

**Comment by aley1** [comment]
Thanks for the tip! I managed to get it to build now. I have building PhotonLibOS separately and then attaching the library to my project (not using FetchContent). I just updated PhotonLibOS c++ version in  CMakeLists.txt  to 17 and build again.With the new output library in my project I can now compile successfully. It should be sufficient for now as I am still testing and prototyping
