### ISSUE TITLE
Repeated Timer and async_run

### ISSUE THREAD

**Issue by aubi1kenobi** [alibaba/PhotonLibOS#133]
Hi guys,
Two, seemingly separated, questions, but related in my use case. The goal is:

- 1. A task sending socket msgs (and doing other things) every 30 seconds (until app stopped)
- 2. Another (independant) task sending socket msgs (to the same server) in parallel
- 3. The two tasks using their own different, ideally, for lowest latency, but to the same remote socket server.

Questions (and I've looked at the few provided examples):

- Q1.  How to use the timer as in point 1 above?
- Q2. photon::coro::run() seems to run synchronously and on the same thread. run_async() seem, on paper, the right candidate. However, when I run two async_run(task1), async_run(task2), task1 seems to run, parallel to the main thread, but without returning for task2 to also start in parallel.
- So, the question really is how to run async two "run and forget" tasks in parallel? I'm not too kin on using the 'thread_create11' that you've used in several examples.
- Q3. The  provided 'socketpool' example doesn't really, clearly, demonsttrate the use of a socket pool. I guess easier to do on a 'server' perspective. I am currently making a separate socket connection for task and task2. How to use the pool, on a 'client' perspective without having to make separate socket connection for each task client? (since ther are both/all talking to the same server?

Txs.

**Comment by beef9999** [comment]
Do you need raw socket or RPC? 

photon::coro is experimental, use thread instead. Have you read this article before? 

https://www.reddit.com/r/cpp/comments/zd2hx1/200_lines_of_code_to_rewrite_the_600000_lines/

**Comment by beef9999** [comment]
Why don’t we have a timer? Because POSIX or C++ std doesn’t provide such.

How do you write a timer with libc?

while (true) { usleep(1000); do(); }

With photon?

while (true) { photon::thread_usleep(1000); do(); }

**Comment by aubi1kenobi** [comment]
@beef9999 Txs for the link. What I got from that is inclusive thoughts on coroutine vs threads. However, while I was waiting for you, i used the 'thread_create11' (I still need to test.
LoL on the timer though. Sleeping = blocking, which is a no go. 
Yes, I need raw sockets.

**Comment by beef9999** [comment]
Any API you found in photon will basically not block the current vcpu( OS thread)

**Comment by aubi1kenobi** [comment]
the 'sleep' blocks oc, but anyway, not too important for the function where it is.
