### ISSUE TITLE
IO_Uring send: Broken pipe

### ISSUE THREAD

**Issue by aubi1kenobi** [alibaba/PhotonLibOS#134]
Hi guys,

Here is the error:

`2023/05/02 15:55:23|ERROR|th=00007F95DBA21B00|/x.cpp:388|sendMessage:SEND FAILURE: errno=32(Broken pipe)`

- 2 separates threads trying to send to the same end point
- Both connects, 1st thread sends and receives msgs no probs.
- as soon as 2nd thread sends a msg, 1st thread gets the above msg when trying to send

**Comment by beef9999** [comment]
There should be no problems, according to your description. Could you show me your code?

**Comment by beef9999** [comment]
And the server you are using is photon as well?

**Comment by aubi1kenobi** [comment]
I don't know what they use for server app, but most probably not. That shouldn't make a difference, should it?

The code is doing nothing else but create two threads, and have the 2 threads connect and send msgs to an ep.

The broken pipe error is really api based. I ddk the ins and outs, will have to dig deep, but it seems two clients cannot send and receivemsgs to the same ep. Idk how the underlying iouring implementation for this use case is.

You don't expose any underlying things, so it's difficult to try different settings.

I would like to try a socket pool, but don't how yet. I did ask, but got no response. 
I tried passing a connection reference from one thread to the other, but thats also not working. still investigating.

**Comment by beef9999** [comment]
It has been through a holiday. Will give you feed back about the connection pool later.

As to the previous broken pipe issue, I think you need to verify your server is working properly, and then show some client code, it will be helpful.

**Comment by aubi1kenobi** [comment]
Thanks. 
The server is a big company with 100s of thousands clients connecting, and maybe 100s of servers to service their clients. There is no experimentation in this line of business, its commercial, and driven by latency and proven hpc tech.

**Comment by lihuiba** [comment]
> Hi guys,
> 
> Here is the error:
> 
> `2023/05/02 15:55:23|ERROR|th=00007F95DBA21B00|/x.cpp:388|sendMessage:SEND FAILURE: errno=32(Broken pipe)`
> 
> * 2 separates threads trying to send to the same end point
> * Both connects, 1st thread sends and receives msgs no probs.
> * as soon as 2nd thread sends a msg, 1st thread gets the above msg when trying to send

I suppose ```x.cpp``` is your app code. 

Does each thread have a separate connection?  Created by new_tcp_socket_client() or new_iouring_tcp_client()?
