### ISSUE TITLE
Unable to compile with IO_URING enabled

### ISSUE THREAD

**Issue by aley1** [alibaba/PhotonLibOS#151]
Hi,

I am trying to build PhotonLibOS with io_uring.
"option(ENABLE_URING "enable io_uring function" ON)" in CMakeList.txt

I am getting errors during build process as per attached image. Will really appreciate it if I can get some pointers on how to resolve this.

![Screenshot from 2023-06-28 10-24-12](https://github.com/alibaba/PhotonLibOS/assets/33714134/1d9381aa-a992-4d88-838f-07f813337734)

**Comment by beef9999** [comment]
The current cmake will download the whole liburing repo by `FETCH_CONTENT`.  Maybe you can remove your local installation in /usr/lib

**Comment by aley1** [comment]
Thanks, removing previous installation resolved the problem.
