### ISSUE TITLE
question: benchmark details

### ISSUE THREAD

**Issue by romange** [alibaba/PhotonLibOS#20]
Hi,

how can we rerun the TCP benchmarks with PhotonLibOS ?
Did you use client and server from https://github.com/alibaba/PhotonLibOS/tree/main/examples/rpc ?

Regarding the results in https://github.com/alibaba/PhotonLibOS#21-tcp
Did you achieve 17.1Gb and 560K qps on a single core? Did I understand correctly?

**Comment by beef9999** [comment]
Wait me 5 minutes, I'm just about to upload the echo server code ...

**Comment by romange** [comment]
Thanks. Btw, very interesting project. Very glad to see that engineers start building high quality asynchronous frameworks for backend development. I developed mine https://github.com/romange/helio  that have somewhat similar goals as [PhotonLibOS](https://github.com/alibaba/PhotonLibOS) but maybe a different design. I wonder if you gonna share HLD doc - maybe we could share ideas. Especially around using io_uring API efficiently.

**Comment by beef9999** [comment]
@romange I have updated the example https://github.com/alibaba/PhotonLibOS/blob/main/examples/perf/net-perf.cpp

In this test I started a coroutine to print QPS every second, but when CPU is 100%, the timing might lost accuracy. So another way is to observe the entire ingress/egress bandwidth of the test machine ( iftop ), and calculate the QPS backwards.

**Comment by beef9999** [comment]
Hi @romange , didn't know you are the author of the dragonfly db. Recently heard of you from some friends in early startups db companies in China. Would you like to chat a little bit about the coroutine lib and io_uring? My email address is on the github homepage.

**Comment by romange** [comment]
sure @beef9999,  I sent you an email.

**Comment by romange** [comment]
i've sent to beef9999 at qq. If you have not got it and it's not in your spam folder, it's quite disturbing.

can you please send me an email  to roman at dragonflydb.io ?
