### ISSUE TITLE
How to join the slack channel

### ISSUE THREAD

**Issue by gongxun0928** [alibaba/PhotonLibOS#202]
I can't find a unexpired invitation link to join the slack channel.  Or you have a separate Chinese community, such as wechat or dingtalk

**Comment by beef9999** [comment]
DingTalk: https://qr.dingtalk.com/action/joingroup?code=v1,k1,WLk3KxUnkyx7aB+9j4FkrK2K45E2g9Si8gjWxUccbQE=&_dt_no_comment=1&origin=11

Slack: https://join.slack.com/t/photonlibos/shared_invite/zt-25wauq8g1-iK_oHMrXetcvWNNhIt8Nkg

**Comment by gongxun0928** [comment]
I can't join dingtalk through this link. Only administrator login is supported.

**Comment by beef9999** [comment]
![image](https://github.com/alibaba/PhotonLibOS/assets/4076315/2bc10d9b-5951-445d-b962-d6bed53e4543)

**Comment by lihuiba** [comment]
![image](https://github.com/alibaba/PhotonLibOS/assets/282919/775c30c7-908e-40ec-a4e3-4c7fa0ac5a78)
try this

**Comment by beef9999** [comment]
![image](https://github.com/alibaba/PhotonLibOS/assets/4076315/81586276-3673-4ea7-ae9b-4caffaa28174)
