### ISSUE TITLE
How do I read a directory and get the list of files?

### ISSUE THREAD

**Issue by aley1** [alibaba/PhotonLibOS#238]
Hi Photon team,

Sorry but I need some help even after looking through examples.

How do I use the photon filesystem to read a directory and get the list of filenames in the directory?

**Comment by beef9999** [comment]
libc has the `readdir` method, and so does photon fs.

https://man7.org/linux/man-pages/man3/readdir.3.html

```c++
photon::fs::DIR* opendir(const char *name);
struct dirent* readdir(DIR *dirp);
```

**Comment by lihuiba** [comment]
If you want to list sub-dir as well, you can use class ```Walker``` in fs/path.h. See fs/test/test.cpp for an example.
```cpp
for (auto file : enumerable(Walker(srcFs, ""))) {
    ...
}
```

**Comment by aley1** [comment]
Thank you all!
