### ISSUE TITLE
Can I ask a question. I read the source code about context switch , but have not seen general register save and pop

### ISSUE THREAD

**Issue by jiangdongzi** [alibaba/PhotonLibOS#239]
How photon achieve this without save and pop general pointers

**Comment by lihuiba** [comment]
By some sort of black magic :-)
We'll describe it in a formal document in the future.

**Comment by jiangdongzi** [comment]
> By some sort of black magic :-) We'll describe it in a formal document in the future.

Can you give some hint, I am  so curious..
