### ISSUE TITLE
switch_context has bug.

### ISSUE THREAD

**Issue by jiangdongzi** [alibaba/PhotonLibOS#243]
![image](https://github.com/alibaba/PhotonLibOS/assets/17529657/350523ba-65d2-4514-8bc2-444a0ae640ff)
printf expect print 123456789, while in fact, it print 12345 changed by another fiber

**Comment by lihuiba** [comment]
The problem is that you use a register (r8), but you don't tell the compiler that you use (modify) it. Just add it  to the clobber-list.

**Comment by jiangdongzi** [comment]
> The problem is that you use a register (r8), but you don't tell the compiler that you use (modify) it. Just add it to the clobber-list.

I modified. Still it prints 12345 changed by another fiber
![image](https://github.com/alibaba/PhotonLibOS/assets/17529657/968c2466-53d7-497e-aa21-4598988117bb)
I think saving "r8" register is the responsibility of `switch_context`, while it seems not to save and restore the "r8" register.

**Comment by jiangdongzi** [comment]
> > The problem is that you use a register (r8), but you don't tell the compiler that you use (modify) it. Just add it to the clobber-list.
> 
> I modified. Still it prints 12345 changed by other fiber ![image](https://user-images.githubusercontent.com/17529657/282732560-968c2466-53d7-497e-aa21-4598988117bb.png) I think saving "r8" register is the responsibility of `switch_context`, while it seems not to save and restore the "r8" register.

Saving r8 is caller's responsibility.

**Comment by lihuiba** [comment]
You must have ```#include "thread.cpp"```. Try not to include it.

The compiler optimizer in this case will find that the modification to r8 seems not to have any effects, and do some global optimization. You can also try some complex C/C++ code that is supposed to use up all registers, and see whether there is any variables have wrong values.

Context switching is a foundation of coroutine/threading. If there were any problem, many programs will fail, including most of the unit tests.
