### ISSUE TITLE
photon.fini() will hang with iouring master engine and signalfd

### ISSUE THREAD

**Issue by yuchen0cc** [alibaba/PhotonLibOS#278]
photon.fini() will hang with iouring master engine and signalfd.

It can be produced by test:

```c++
TEST(IouringTest, Init) {
    auto ret = photon::init(photon::INIT_EVENT_IOURING | photon::INIT_EVENT_SIGNAL, photon::INIT_IO_NONE);
    DEFER(photon::fini());
    EXPECT_EQ(0, ret);
}
```

It blocks on https://github.com/alibaba/PhotonLibOS/blob/main/io/iouring-wrapper.cpp#L344 and `m_eventfd` is not non-blocked.

**Comment by yuchen0cc** [comment]
@beef9999 cc

**Comment by beef9999** [comment]
Can you try this code in 6.x kernel. Because the CI can pass.

**Comment by beef9999** [comment]
I tested your code in 6.4.12-1.el8.elrepo.x86_64 kernel.

It didn't hang.

**Comment by yuchen0cc** [comment]
@beef9999 It happens to be a kernel related issue.
The above test hangs in `4.19.91` and `5.10.134`, but works well in `5.15.0`, `5.18.15` and `6.6.2`.

I will close this issue.
