### ISSUE TITLE
Issue building on Ubuntu/ARM

### ISSUE THREAD

**Issue by sptrakesh** [alibaba/PhotonLibOS#308]
Hello,

I am trying to build Photon on Ubuntu/ARM combination (noble and gcc13).  Compilation fails (version 0.7.3) with the following error:

```
1.814 /opt/PhotonLibOS/include/photon/net/socket.h:168:36: error: static assertion failed: Endpoint size incorrect
1.814   168 |     static_assert(sizeof(EndPoint) == 18, "Endpoint size incorrect");
1.814       |                   ~~~~~~~~~~~~~~~~~^~~~~
1.815 /opt/PhotonLibOS/include/photon/net/socket.h:168:36: note: the comparison reduces to '(20 == 18)’
```

**Comment by beef9999** [comment]
```struct __attribute__ ((packed)) EndPoint {};```

gcc 13 doesn't allow this syntax? Could you try to move `__attribute__ ((packed))` after `{}` ?

**Comment by lihuiba** [comment]
> /opt/PhotonLibOS/include/photon/common/alog-functionptr.h:29:5: error: there are no arguments to 'free' that depend on a template parameter, so a declaration of 'free' must be available [-fpermissive]

try adding ```#include <stdlib.h>```

**Comment by lihuiba** [comment]
> /opt/PhotonLibOS/rpc/test/test-rpc-message.cpp:241: Failure

I'll take look at this.

**Comment by lihuiba** [comment]
> {addr: 0xaaaac22acd80, len: 281474211218720}

This length is not correct.
Is the error deterministically reproducible?
If so, can you add a log output as following to see more detail:
```diff
@@ -232,6 +232,7 @@ TEST(rpc, variable_length_serialization) {
     VariableLengthMessage m_send;
     m_send.a = 1;
     m_send.b.assign(send_string);
+    LOG_DEBUG(VALUE(m_send.b._ptr), VALUE(m_send.b._len));

     photon::rpc::SerializerIOV s_send;
     s_send.serialize(m_send);
```

**Comment by sptrakesh** [comment]
This is weird.  The invalid length looks like the side effect of an uninitialised variable.  Adding the log somehow seems to  remove that issue.  I tried this a few times, without the log statement the test will fail, while with the log statement it will pass.

**Comment by lihuiba** [comment]
This sounds like a compiler bug. Can you make another try by replacing the log with an empty inline assembly as follow:
```diff
@@ -232,6 +232,7 @@ TEST(rpc, variable_length_serialization) {
     VariableLengthMessage m_send;
     m_send.a = 1;
     m_send.b.assign(send_string);
+    asm volatile ("");

     photon::rpc::SerializerIOV s_send;
     s_send.serialize(m_send);
```

**Comment by sptrakesh** [comment]
> This sounds like a compiler bug. Can you make another try by replacing the log with an empty inline assembly as follow:
> 
> ```diff
> @@ -232,6 +232,7 @@ TEST(rpc, variable_length_serialization) {
>      VariableLengthMessage m_send;
>      m_send.a = 1;
>      m_send.b.assign(send_string);
> +    asm volatile ("");
> 
>      photon::rpc::SerializerIOV s_send;
>      s_send.serialize(m_send);
> ```
> 
> This acts like a barrier to (hopefully) prevent some aggressive optimization.

No, does not work.  Adding the log still works...

**Comment by lihuiba** [comment]
> No, does not work. Adding the log still works...

try this:
asm volatile ("" : "+r"(m_send.b._ptr), "+r"(m_send.b._len));

**Comment by sptrakesh** [comment]
> > No, does not work. Adding the log still works...
> 
> try this: asm volatile ("" : "+r"(m_send.b._ptr), "+r"(m_send.b._len));

Yes, this works.

**Comment by lihuiba** [comment]
> > try this: asm volatile ("" : "+r"(m_send.b._ptr), "+r"(m_send.b._len));
> 
> Yes, this works.

So it confirms that the compiler has bugs. This piece of assembly code is actually a noop. It only prevents the optimizer from reordering of load / stores across the line.
