### ISSUE TITLE
comparison with lib_fiber

### ISSUE THREAD

**Issue by dragon-zhang** [alibaba/PhotonLibOS#32]
can you guys add a comparison with `lib_fiber`? I mean `lib_fiber` module in https://github.com/acl-dev/acl

and https://github.com/idealvin/cocoyaxi

**Comment by beef9999** [comment]
The second one has been tested before. We are better.

**Comment by dragon-zhang** [comment]
Is there any progress compared with https://github.com/acl-dev/acl/tree/master/lib_fiber ?

Besides, how about comparing `bthread` in [brpc](https://github.com/apache/incubator-brpc) ?

**Comment by beef9999** [comment]
I have tested lib_fiber's tcp echo server, and updated its performance results into our data sheet. As we expected, it's still slower than us.
```c++
#include "acl_cpp/lib_acl.hpp"
#include "fiber/go_fiber.hpp"

void run(void) {
  const char* addr = "0.0.0.0:9527";
  acl::server_socket server;
  if (!server.open(addr)) {
    return;
  }

  go[&] {  // Create one server coroutine to wait for connection.
    while (true) {
      acl::socket_stream* conn = server.accept();
      if (conn) {
        go[=] {  // Create one client coroutine to handle the connection.
          char buf[512];
	  while(true) {
            int ret = conn->read(buf, sizeof(buf), false);
            if (ret > 0) {
              (void) conn->write(buf, ret);
            }
	  }
          delete conn;
        };
      }
    }
  };

  acl::fiber::schedule();  // Start the coroutine scheculde process.
}

int main() {
  run();
}
```
```bash
g++  -O2 -Ilib_fiber/cpp/include/ -Ilib_acl_cpp/include/ server.cpp -o server -Lbuild/lib -l:libacl_cpp.a -l:libfiber_cpp.a -l:libfiber.a -l:libprotocol.a  -l:libacl.a -ldl  -lpthread
```

As to brpc, I only found a rpc echo server, not a tcp one. So unable to do the tests. I imagine the data would still be the same.

> Nothing is faster than light, and no coroutine lib is faster than Photon

**Comment by dragon-zhang** [comment]
Amazing ! I will continue to pay attention to this project.
