### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by jiangdongzi** [alibaba/PhotonLibOS#35]
[`gmake[2]: *** [CMakeFiles/boost-populate.dir/build.make:99: boost-populate-prefix/src/boost-populate-stamp/boost-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/boost-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
CMake Error at /usr/share/cmake-3.22/Modules/FetchContent.cmake:1087 (message):
  Build step for boost failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1216:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1216 (cmake_language)
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1259 (FetchContent_Populate)
  CMakeLists.txt:97 (FetchContent_MakeAvailable)`](https://github.com/marius-team/marius/issues/16)

![image](https://user-images.githubusercontent.com/17529657/178246890-b26c962b-c934-4030-931b-fb3491d65fd4.png)

与 https://github.com/marius-team/marius/issues/16  看起来差不多

**Comment by beef9999** [comment]
Please identify your cmake version, and OS type and version.

If you can't access the original boost download link, you may switch to another available link by modifying the `Fetch boost` section in `CMakeList.txt` (remember to update the md5 as well).

**Comment by jiangdongzi** [comment]
> 

MD5 is d41d8cd98f00b204e9800998ecf8427e in my machine, not 38813f6feb40387dfe90160debd71251, you can try.

**Comment by beef9999** [comment]
@jiangdongzi 

# wget https://boostorg.jfrog.io/artifactory/main/release/1.75.0/source/boost_1_75_0.tar.gz

# md5sum boost_1_75_0.tar.gz
38813f6feb40387dfe90160debd71251  boost_1_75_0.tar.gz
