### ISSUE TITLE
question: how to use multi-core when writing applications with photonlibos

### ISSUE THREAD

**Issue by cllh** [alibaba/PhotonLibOS#38]
Looks like photonlibos can only use one CPU core. If I want to write a service running on a multi-core server, how can I use all of the cores?

Can you give an example?

**Comment by beef9999** [comment]
@cllh Please see this example https://github.com/alibaba/PhotonLibOS/pull/39

In this exmaple, every new connection will be dispatched / migrated to one of the multiple vcpus. You may run the echo client with Ping-pong mode, and check the CPU usage.

Note this is not the ultimate version of multi-core support, the full automatic coroutine scheduling as Golang did (also called task stealing) is still under development. For now the low level mechanism is complete (for example, `photon::mutex`, `photon::spinlock`, and the thread-safe version of `thread_usleep_defer` instead of `thread_usleep`), but you have invoke them manually.

**Comment by cllh** [comment]
awesome, looking forwards to the full automatic coroutine scheduling enhancement like golang.

when will this feature be available?

**Comment by jiangdongzi** [comment]
> Note this is not the ultimate version of multi-core support, the full automatic coroutine scheduling like Golang did (also called task stealing)
Does this mean at current time, one certain coroutine can be only scheduled by one certain thread?

**Comment by beef9999** [comment]
@jiangdongzi Please see this example https://github.com/alibaba/PhotonLibOS/pull/39

`thread_migrate` allows you to migrate one coroutine from one vcpu to another. （vcpu = OS thread）

Besides, you can use `thread/workerpool.h`. It's also a multi-thread implementation.

**Comment by beef9999** [comment]
I can achieve 2.4M QPS by running this modified example, with the CPU usage of 800%.

**Comment by lihuiba** [comment]
> awesome, looking forwards to the full automatic coroutine scheduling enhancement like golang.
> 
> when will this feature be available?

The development of work-stealing has already started, and might be finished by this autumn, but there's no hard deadline.

**Comment by jiangdongzi** [comment]
> > awesome, looking forwards to the full automatic coroutine scheduling enhancement like golang.
> > when will this feature be available?
> 
> The development of work-stealing has already started, and might be finished by this autumn, but there's no hard deadline.

Well, I want to know when will you release detailed document?

**Comment by lihuiba** [comment]
> > > awesome, looking forwards to the full automatic coroutine scheduling enhancement like golang.
> > > when will this feature be available?
> > 
> > 
> > The development of work-stealing has already started, and might be finished by this autumn, but there's no hard deadline.
> 
> Well, I want to know when will you release detailed document?

Currently we are focused on completing the feature set. 

Please read the header files (and possibly some cpp files) for reference, for now.

**Comment by lihuiba** [comment]
> > > awesome, looking forwards to the full automatic coroutine scheduling enhancement like golang.
> > > when will this feature be available?
> > 
> > 
> > The development of work-stealing has already started, and might be finished by this autumn, but there's no hard deadline.
> 
> Well, I want to know when will you release detailed document?

And we'll write detailed document later, when major features are implemented and their interfaces get stable.
