### ISSUE TITLE
do you plan to support on windows systems?

### ISSUE THREAD

**Issue by rooong** [alibaba/PhotonLibOS#40]
do you plan to support windows systems?

**Comment by beef9999** [comment]
See https://github.com/alibaba/PhotonLibOS#about-photon 

Because this project was designed for cloud software, and most of the cloud infrastructure is base on Linux. For now, we don't have strong motivation to work out a Windows version, until we have enough support from the open-source community.

**Comment by zllangct** [comment]
vlang使用它作为协程基础库，是否可以推进合作共建

**Comment by beef9999** [comment]
@zllangct 请问你是vlang 的开发者吗。另外我邮件地址在github首页，欢迎交流

**Comment by lihuiba** [comment]
> vlang使用它作为协程基础库，是否可以推进合作共建

@zllangct 
巧了，就刚过去的周末我安装了一台windows机器以及visual studio社区版本，打算做一做windows支持。我注意到V语言使用tcc、mingw、以及VC。根据你的经验，你建议如何做这方面的工作？

**Comment by lihuiba** [comment]
@rooong @zllangct The threading part of photon now supports Windows via mingw (msys2). See https://github.com/alibaba/PhotonLibOS/pull/185/files#diff-f0db3c6fae5cc5fe519ada39d68af66b8c177096a3ee36c0d92893be964cf34c details.
