### ISSUE TITLE
init iouring failed

### ISSUE THREAD

**Issue by dean-river** [alibaba/PhotonLibOS#46]
hello i follow the instractions of Build in the file README.md. But when i run  PhotonLibOS/build/output/simple-example，i got this error bellow:
`2022/08/02 11:06:40|INFO |th=0000000000641FB0|/home/root/workspace/PhotonLibOS/io/iouring-wrapper.cpp:495|new_iouring:Init event engine: iouring [is_master=1]
2022/08/02 11:06:40|WARN |th=0000000000641FB0|/home/root/workspace/PhotonLibOS/io/iouring-wrapper.cpp:74|init:iouring: current user has no permission to set unlimited RLIMIT_MEMLOCK, change to root?
2022/08/02 11:06:46|ERROR|th=0000000000641FB0|/home/root/workspace/PhotonLibOS/io/iouring-wrapper.cpp:84|init:iouring: failed to init queue errno=38(Function not implemented)
2022/08/02 11:06:46|INFO |th=0000000000641FB0|/home/root/workspace/PhotonLibOS/io/iouring-wrapper.cpp:49|~iouringEngine:Finish event engine: iouring [m_master=1]
2022/08/02 11:06:46|ERROR|th=0000000000641FB0|/home/root/workspace/PhotonLibOS/examples/simple/simple.cpp:46|main:failed to init photon environment`

i gdb follow step into here
`static inline int ____sys_io_uring_setup(unsigned entries,
					 struct io_uring_params *p)
{
#ifdef CONFIG_NOLIBC
	return __arch_impl_io_uring_setup(entries, p);
#else
	int ret;
	ret = syscall(__NR_io_uring_setup, entries, p);
	return (ret < 0) ? -errno : ret;
#endif
}`

syscall(__NR_io_uring_setup, entries, p); return -1， errno=38(Function not implemented)

my system is：CentOS Linux release 8.5.2111
linux kernel version is： 4.18.0

**Comment by beef9999** [comment]
https://github.com/alibaba/PhotonLibOS/blob/221f0d156680f790e07b0bdad64c16fbcc7a3a92/examples/simple/simple.cpp#L38-L44

1. Your current user has no permission to set rlimit, just use root?
2. Update kernel version, not less than 5.8 to run iouring

```
dnf install https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
dnf --enablerepo=elrepo-kernel install kernel-ml
dnf --enablerepo=elrepo-kernel install kernel-ml-{devel,headers}
```

**Comment by dean-river** [comment]
update kernel is too hard for me , I change event_engine to INIT_EVENT_EPOLL, like said on comments.
but when i rebuild i got a link error 
`$ make
[  7%] Built target uring
[ 10%] Built target easy_weak
[ 82%] Built target photon_obj
[ 83%] Built target photon
[ 85%] Built target photon_static
[ 86%] Linking CXX executable ../output/net-perf
CMakeFiles/net-perf.dir/perf/net-perf.cpp.o: In function `main':
/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:238: undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
CMakeFiles/net-perf.dir/perf/net-perf.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:31: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:32: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:33: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:34: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:35: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
CMakeFiles/net-perf.dir/perf/net-perf.cpp.o:/home/root/workspace/PhotonLibOS/examples/perf/net-perf.cpp:36: more undefined references to `google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/net-perf.dir/build.make:105: output/net-perf] Error 1
make[1]: *** [CMakeFiles/Makefile2:266: examples/CMakeFiles/net-perf.dir/all] Error 2
make: *** [Makefile:111: all] Error 2`

gflags is installed 

`$ yum install gflags-devel
Last metadata expiration check: 3:44:10 ago on Tue 02 Aug 2022 04:51:28 AM UTC.
Package gflags-devel-1:2.1.2-7.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
`

**Comment by dean-river** [comment]
update kernel is not easy for me， i change the event_engine to epool,  now it ok, but i find two write error(or bug) in simple.cpp

<img width="960" alt="image" src="https://user-images.githubusercontent.com/7499154/182347413-4c736c0d-f724-44f7-b73a-70125330f2b1.png">

line 70: should be
    if (server == nullptr) {

line 87 should be
    if (client == nullptr) {

**Comment by beef9999** [comment]
Yes, it's apparently a bug. Thanks for reporting.
