### ISSUE TITLE
io_uring master_event_engine wait_and_fire_events can't wake up, leading to lock cost long time

### ISSUE THREAD

**Issue by yarthur1** [alibaba/PhotonLibOS#520]
in my test, when i use io_uring engine, i found mutex.lock() cost over 10S, if i use epoll  engine, likely no this problem.  
![image](https://github.com/alibaba/PhotonLibOS/assets/30923528/61af7010-9234-452d-be66-19835ff49102)

if i modify idle_stub func max timeout=1024us,  mutex.lock() cost almostly 1ms,sometimes 2ms, 3ms.
![image](https://github.com/alibaba/PhotonLibOS/assets/30923528/b0098a08-28e8-44ff-905f-d399d7ff7f0e)
![image](https://github.com/alibaba/PhotonLibOS/assets/30923528/c62f53d6-305b-4edf-873b-96b5c45c57ce)
[code.zip](https://github.com/user-attachments/files/15982582/code.zip)

env: photon v0.7.3，liburing-2.3.0，os  5.10.112-005.ali5000.alios7.x86_64

thank you for look my proble

**Comment by beef9999** [comment]
Can you provide the example code, and what is your kernel version?

**Comment by yarthur1** [comment]
> Can you provide the example code, and what is your kernel version?

i upload code.zip

**Comment by beef9999** [comment]
Your code is too complicated, it seems you are trying to dispatch tasks by WorkPool, but why using the queue?

Maybe you can join the DingTalk or Slack group to discuss.
