### ISSUE TITLE
More detailed documents?

### ISSUE THREAD

**Issue by mankouzhuya** [alibaba/PhotonLibOS#54]
doc目录下就一张图片

**Comment by beef9999** [comment]
We will build an independent website for developers to view the documents in the future.

Before that, you may
1. Read some of the explanations for each modules, for example, https://github.com/alibaba/PhotonLibOS/blob/main/io/README.md
2. Read the header files directly. Most of them have comments.

**Comment by mankouzhuya** [comment]
got it

**Comment by beef9999** [comment]
The 3 examples are very good tutorials for new developers to get familiar with photon.
