### ISSUE TITLE
io-perf not working

### ISSUE THREAD

**Issue by ErvinXie** [alibaba/PhotonLibOS#556]
This io-perf is not working. 
```bash
./io-perf --disk_path=/dev/sdb  --disk_size=3000000000000 --io_depth=128 --io_size=4096 --io_uring 
2024/09/12 03:08:45.158161|INFO |th=0000000000000000|io-perf.cpp:79|main:Specify disk /dev/sdb size 3000000000000
2024/09/12 03:08:45.158495|ERROR|th=0000556A9B66DEA0|photon.cpp:87|__photon_init:All master engines init failed
2024/09/12 03:08:45.158502|ERROR|th=0000556A9B66DEA0|io-perf.cpp:87|main:init failed
```

**Comment by ErvinXie** [comment]
It works after remove `--io_uring`, how to use `--io_uring`?

**Comment by lihuiba** [comment]
Have your turned on iouring? (with PHOTON_ENABLE_URING=ON when you build Photon)

And what is your kernel version? IO_uring requires recent kernel support.

**Comment by ErvinXie** [comment]
Thank you for the fast reply, I checked the [build guide](https://photonlibos.github.io/docs/introduction/how-to-build#case-1-staitcally-build-all-third-party-libs) and get it working.
