### ISSUE TITLE
测试例子

### ISSUE THREAD

**Issue by zhengshuxin** [alibaba/PhotonLibOS#56]
能否提供更多的简单示例？

**Comment by beef9999** [comment]
Hi, we appreciate English communication in this project, for the convenience of developers worldwide.

What's your issue when running the example?

**Comment by zhengshuxin** [comment]
Can you please provide more samples?

**Comment by beef9999** [comment]
What kind of examples do you want? File IO ? HTTP server ?

**Comment by beef9999** [comment]
Personally I think the echo server example is sophisticated enough...
