### ISSUE TITLE
Do coroutines support local storage (like thread_local)?

### ISSUE THREAD

**Issue by jiangdongzi** [alibaba/PhotonLibOS#58]

**Comment by beef9999** [comment]
May I know the reason you want this feature? Is that you want better performance when sharing resource among coroutines within a unique cpu core?

**Comment by beef9999** [comment]
BTW, we used to migrate some thread-based projects to coroutines with Photon, for example, rocksdb.
No matter of std::thread, std::mutex,  std::condition_variable and so on, most of the components are very easy to transform to Photon's equivalents, but `thread_local` is still the thing we are uncertain how to deal with.
If you have met the same problem, we would like to hear your situation.

**Comment by lihuiba** [comment]
@jiangdongzi Photo supports a very limited form of coroutine local storage, via:
```c++
void* thread_get_local();
void thread_set_local(void* local);
```

**Comment by jiangdongzi** [comment]
> 顺便说一句，我们曾经将一些基于线程的项目迁移到Photon的协程中，例如rocksdb。无论std：：thread，std：：mutex，std：：condition_variable等等，大多数组件都很容易转换为Photon的等价物，但仍然是我们不确定如何处理的事情。如果您遇到同样的问题，我们希望听到您的情况。`thread_local`



> May I know the reason you want this feature? Is that you want better performance when sharing resource among coroutines within a unique cpu core?

In our business, we hash user to specified thread via uid, every business thread has its own specified data. While coroutine maybe transfered from std::threadA to std::threadB, this will result in problem.

**Comment by jiangdongzi** [comment]
> BTW, we used to migrate some thread-based projects to coroutines with Photon, for example, rocksdb. No matter of std::thread, std::mutex, std::condition_variable and so on, most of the components are very easy to transform to Photon's equivalents, but `thread_local` is still the thing we are uncertain how to deal with. If you have met the same problem, we would like to hear your situation.

In our business, we hash user to specified thread via uid, every business thread has its own specified data. While coroutine maybe transfered from std::threadA to std::threadB, this will result in problem.

**Comment by lihuiba** [comment]
> In our business, we hash user to specified thread via uid, every business thread has its own specified data. While coroutine maybe transfered from std::threadA to std::threadB, this will result in problem.

Coroutines are not necessarily transferred from one std::thread to another, unless you instruct photon to do so. It is possible that you can still use thread_local variables?

**Comment by jiangdongzi** [comment]
> > In our business, we hash user to specified thread via uid, every business thread has its own specified data. While coroutine maybe transfered from std::threadA to std::threadB, this will result in problem.
> 
> Coroutines are not necessarily transferred from one std::thread to another, unless you instruct photon to do so. It is possible that you can still use thread_local variables?

Yeah, if this, there is no problem. But do you have plans of auto transferring coroutines? Such as std::threadA is busy, and std::threadB is idle.

**Comment by lihuiba** [comment]
> But do you have plans of auto transferring coroutines? Such as std::threadA is busy, and std::threadB is idle.
Yes, we'll support automatic load balancing of threads (coroutines) among vCPUs (std::threads) by work-stealing. Perhaps within this year.

**Comment by beef9999** [comment]
@jiangdongzi TLS support has been added, similar to C++11 `thread_local`usage. See [doc](https://github.com/alibaba/PhotonLibOS/blob/main/doc/thread-local.md)
