### ISSUE TITLE
Is there a plan to support RDMA ?

### ISSUE THREAD

**Issue by dragon-zhang** [alibaba/PhotonLibOS#59]
see https://github.com/apache/incubator-brpc/pull/1836

**Comment by beef9999** [comment]
Interesting. Would you like to chat a little bit? My email address is on my home page.

**Comment by Coldwings** [comment]
We are planing to provides RDMA supports via rSocket API, as a part of photon in not too far future.
rSocket is different to kernel socket API,  when users do needs zero copy feature, the buffer should take from RMDA ring.
That may needs to take some efforts before RPC can make use of it.

**Comment by dragon-zhang** [comment]
DPDK is also a good option because it is not limited to hardware.

**Comment by lihuiba** [comment]
> DPDK is also a good option because it is not limited to hardware.

Yes, and user-space TCP may be an issue.

**Comment by lihuiba** [comment]
> DPDK is also a good option because it is not limited to hardware.

Photon now has support for DPDK and user-space TCP (via f-stack), as well as RDMA (via SMC-r).

**Comment by chenBright** [comment]
@beef9999 @lihuiba Does Alibaba have any practical applications of DPDK and user-space TCP (via f-stack) internally?
