### ISSUE TITLE
What could happen if PHOTON INIT FAILED?

### ISSUE THREAD

**Issue by ErvinXie** [alibaba/PhotonLibOS#591]
Hello, I am using photon as an async storage backend. I started an io thread using std::thread and did something like this. 
```c++
int ret = photon::init(ev_engine, io_engine, photon::PhotonOptions{.libaio_queue_depth = 512});
if (ret != 0) {
      LOG_ERROR("PHOTON INIT FAILED");
      exit(1);
}
DEFER(photon::fini());
```
And 
```
2024/10/08 09:54:54.264386|ERROR|th=00007FFD94000F30|photon.cpp:87|__photon_init:All master engines init failed
2024/10/08 09:54:54.264431|ERROR|th=00007FFD94000F30|async_store.cpp:214|io_dealer:PHOTON INIT FAILED
```

It works completely fine when I use it in cpp. This error only occurs when I call it from python using pybind11. 
Could you provide some idea on how to debug this?

**Comment by beef9999** [comment]
ev_engine is epoll (1) ?

**Comment by lihuiba** [comment]
What are the actual values of ```ev_engine``` and ```io_engine```?

**Comment by ErvinXie** [comment]
I checked the parameters, it turns out that I passed some wrong args. Thanks for your help!
