### ISSUE TITLE
build test failed on windows wsl ubuntu 22.04 

### ISSUE THREAD

**Issue by cagev** [alibaba/PhotonLibOS#66]
build env: 
ubuntu 22.04  in windows wsl 
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

/home/arthur/work/PhotonLibOS/fs/test/test.cpp: In function ‘void malloc_hook()’:
/home/arthur/work/PhotonLibOS/fs/test/test.cpp:693:5: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘malloc_hook’?
  693 |     __malloc_hook = my_malloc;
      |     ^~~~~~~~~~~~~
      |     malloc_hook
/home/arthur/work/PhotonLibOS/fs/test/test.cpp:694:5: error: ‘__free_hook’ was not declared in this scope
  694 |     __free_hook = my_free;
      |     ^~~~~~~~~~~
/home/arthur/work/PhotonLibOS/fs/test/test.cpp: In function ‘void malloc_unhook()’:
/home/arthur/work/PhotonLibOS/fs/test/test.cpp:698:5: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘malloc_hook’?
  698 |     __malloc_hook = old_malloc;
      |     ^~~~~~~~~~~~~
      |     malloc_hook
/home/arthur/work/PhotonLibOS/fs/test/test.cpp:699:5: error: ‘__free_hook’ was not declared in this scope
  699 |     __free_hook = old_free;
      |     ^~~~~~~~~~~
/home/arthur/work/PhotonLibOS/fs/test/test.cpp: In function ‘void init_hook()’:
/home/arthur/work/PhotonLibOS/fs/test/test.cpp:703:18: error: ‘__malloc_hook’ was not declared in this scope; did you mean ‘malloc_hook’?
  703 |     old_malloc = __malloc_hook;
      |                  ^~~~~~~~~~~~~
      |                  malloc_hook
/home/arthur/work/PhotonLibOS/fs/test/test.cpp:704:16: error: ‘__free_hook’ was not declared in this scope
  704 |     old_free = __free_hook;
      |                ^~~~~~~~~~~
[ 80%] Linking CXX executable ../../../output/client_perf

**Comment by beef9999** [comment]
It was because `__malloc_hook ` was removed from glibc 2.34, and Ubuntu 22 is using glibc 2.35.

We will upload a fix for this.

**Comment by beef9999** [comment]
Fixed
