### ISSUE TITLE
Feature Request: Support for Kernel Side Polling in io_uring

### ISSUE THREAD

**Issue by f0cii** [alibaba/PhotonLibOS#681]
Description:

Currently, PhotonLibOS supports io_uring, which is a great feature for asynchronous I/O operations. However, it lacks support for binding CPU and Kernel Side Polling. We would like to request the addition of this feature to enhance performance and efficiency.

Key Explanation:

IORING_SETUP_SQPOLL allows the application to update the submission queue (SQ) ring and fill a new submission queue entry (SQE). The kernel thread sqthread will automatically complete the submission, eliminating the need for the application to call io_uring_enter() for every I/O submission.

The application can bind a specific CPU using IORING_SETUP_SQ_AFF and sq_thread_cpu. Additionally, to save CPU resources during idle periods with no I/O, the kernel thread will automatically sleep after a certain time. When the application issues new I/O, it can wake up the kernel thread using IORING_ENTER_SQ_WAKEUP, which is already encapsulated in liburing.

Reference:
For more details, please refer to the following link: [Kernel Side Polling Documentation](https://github.com/0voice/kernel_new_features/blob/main/io_uring/%E6%96%87%E7%AB%A0/%E4%B8%8B%E4%B8%80%E4%BB%A3%E5%BC%82%E6%AD%A5%20IO%20io_uring%20%E6%8A%80%E6%9C%AF%E8%A7%A3%E5%AF%86.md#kernel-side-polling)

Benefits:
Implementing this feature will improve the efficiency of I/O operations in PhotonLibOS, allowing applications to better utilize CPU resources and reduce overhead during idle periods.

Thank you for considering this feature request!

**Comment by lihuiba** [comment]
```cpp
auto event = INIT_EVENT_IOURING        | 
             INIT_EVENT_IOURING_SQPOLL |  
             INIT_EVENT_IOURING_SQ_AFF ;
photon::init(event, INIT_IO_NONE, {
    .iouring_sq_thread_cpu = xxxx,
    .iouring_sq_thread_idle = yyyy;
});
```

**Comment by lihuiba** [comment]
@f0cii Please try this feature and give some feedbacks on performance change(s). Thanks!
