### ISSUE TITLE
有关于hook系统调用的计划吗

### ISSUE THREAD

**Issue by xinhaojie** [alibaba/PhotonLibOS#687]
我们在找一个生产换进关于应用的携程库，看到PhotonLibOS好像还不支持hook系统调用。但是我们需要在流程中调用其他的库，其他的库可能是同步处理的，比如mysql，这样用PhotonLibOS就不是很方便，请问有解决方案么，或者有hook系统调用的计划么

**Comment by Coldwings** [comment]
由于实际使用中协程与线程仍有差异，直接hook glibc API可能会造成更多的问题且难以发现和解决，目前没有计划提供此类hook。

相对的，目前主流的异步/协程/用户态线程框架或库往往都会提供至少一种用于在流程中发起会阻塞的调用的途径。Photon中提供了WorkPool，可以在协程上下文中，通过一组线程池来专门执行阻塞调用，而不阻塞当前协程环境。对于没有提供异步API的调用，此类方式是一种比较合适的通用解决方案，比较推荐使用。

**Comment by xinhaojie** [comment]
了解，谢谢
