### ISSUE TITLE
gcc version

### ISSUE THREAD

**Issue by Lovening** [alibaba/PhotonLibOS#72]
Hello, thanks for open source such a great program, I would like to ask which version supports the lowest gcc, because I may use it on an embedded development board

**Comment by beef9999** [comment]
gcc 4.9.2 with C++ 11

But you have to manually disable some C++14 features, for example, alog-stdstring.h.

**Comment by beef9999** [comment]
BTW, gcc 4.9.2 supports C++1y, which is a middle version between C++11 and C++14. It supports all of the C++14 features that Photon requires. You you may also use 4.9.2 with C++1y

**Comment by lihuiba** [comment]
> Hello, thanks for open source such a great program, I would like to ask which version supports the lowest gcc, because I may use it on an embedded development board

Do you use ARM64 or x86_64 in your embedded environment?

**Comment by Lovening** [comment]
> 



> > Hello, thanks for open source such a great program, I would like to ask which version supports the lowest gcc, because I may use it on an embedded development board
> 
> Do you use ARM64 or x86_64 in your embedded environment?

ARM64

**Comment by Lovening** [comment]
> BTW, gcc 4.9.2 supports C++1y, which is a middle version between C++11 and C++14. It supports all of the C++14 features that Photon requires. You you may also use 4.9.2 with C++1y

OK. thanks
