### ISSUE TITLE
About tuple_assitance::callable

### ISSUE THREAD

**Issue by 4kangjc** [alibaba/PhotonLibOS#98]
* 不支持`noexcept`，`&`， `&&`, `volatile`等
*  ```cpp
   template <class F>
   struct callable<F&> : public callable<F> {};
   
   template <class F>
   struct callable<F&&> : public callable<F> {};
    ```
不如直接`std::remove_cvref_t`(自己封装一个) ?
* ....
* 如果只是应用于`thread11`和`apply`，可以参考一下标准库？`clang`或者`gcc`的都行，我认为`callable`槽点有点多，hmm，不如去掉, C++17以下可以用`std::__invoke`？

[std::invoke](https://en.cppreference.com/w/cpp/utility/functional/invoke)
[std::apply](https://en.cppreference.com/w/cpp/utility/apply)

**Comment by Coldwings** [comment]
谢谢建议。

`callable`只是用于提供一个函数指针、成员函数指针、functor的通用表示来简化实现部分。主要意义用于提取`return_type`，`arguments`。主要考虑内部使用，实现之初考虑或许并不十分完备。

由于std::invoke和std::apply作为标准库，均需要C++17或以上，`std::remove_cvref`更是C++20标准引入的，而代码在对应的部分场景中主要考虑兼容C++1y（in GCC492）版本，故未直接使用。

参考现有STL的实现是个很好的建议，后续也会考虑对其进行调整，也欢迎您提交更好实现的PR。谢谢。

**Comment by 4kangjc** [comment]
> 谢谢建议。
> 
> `callable`只是用于提供一个函数指针、成员函数指针、functor的通用表示来简化实现部分。主要意义用于提取`return_type`，`arguments`。主要考虑内部使用，实现之初考虑或许并不十分完备。
> 
> 由于std::invoke和std::apply作为标准库，均需要C++17或以上，`std::remove_cvref`更是C++20标准引入的，而代码在对应的部分场景中主要考虑兼容C++1y（in GCC492）版本，故未直接使用。
> 
> 参考现有STL的实现是个很好的建议，后续也会考虑对其进行调整，也欢迎您提交更好实现的PR。谢谢。

OK, I am willing to submit a PR!
